// p2/js/_gen_obs_meta.mjs — 產生觀察庫編輯器要用的靜態資料：
//   p2/js/questions_layout.js  — 每部位的 section 順序＋題目順序（保留 §2「順序」）
//   p2/js/ref_dims.js          — obsId → 被哪些維度引用 + 哪些 match 值被用到（刪除保護 §11 A/B）
// 純讀 p2_seed/。不寫任何 Firestore、不改引擎。
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DIMS } from '../../js/core.js';

const __dir = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dir, '..', '..');
const Q = JSON.parse(readFileSync(join(REPO, 'p2_seed', 'rbf1_settings_questions.json'), 'utf8'));
const live = JSON.parse(readFileSync(join(REPO, 'p2_seed', 'rbf1_settings_rules.json'), 'utf8'));

// 1) 版面/順序：part -> [ {label, qIds:[...]} ]（保留原陣列順序）
const layout = {};
for (const part of Object.keys(Q)) {
  layout[part] = (Q[part].sections || []).map(s => ({ label: s.label, qIds: (s.qs || []).map(q => q.id) }));
}
writeFileSync(join(__dir, 'questions_layout.js'),
  '// AUTO-GENERATED by _gen_obs_meta.mjs — 初始 section/題目順序（之後以 config/questionsLayout 為準）\nwindow.QUESTIONS_LAYOUT = ' + JSON.stringify(layout) + ';\n');

// 2) 引用反查：obsId -> {dims:Set, vals:Set}
const refDims = {};   // obsId -> [dimName...]
const refVals = {};   // obsId -> [matchValue...]
function walk(node, dimName) {
  if (node == null) return;
  if (Array.isArray(node)) { node.forEach(n => walk(n, dimName)); return; }
  if (typeof node !== 'object') return;
  if (node.ref !== undefined) {
    (refDims[node.ref] = refDims[node.ref] || new Set()).add(dimName);
    const arr = Array.isArray(node.match) ? node.match : [node.match];
    arr.forEach(v => (refVals[node.ref] = refVals[node.ref] || new Set()).add(v));
    return;
  }
  ['items', 'each', 'rule', 'item', 'veto', 'condition'].forEach(k => { if (node[k]) walk(node[k], dimName); });
  if (node.group && node.items) walk(node.items, dimName);
  if (node.veto && Array.isArray(node.veto)) node.veto.forEach(v => v.condition && walk(v.condition, dimName));
}
live.forEach((d, i) => { const nm = DIMS[i].dn; Object.values(d.parts).forEach(p => walk(p, nm)); });

const refDimsOut = {}, refValsOut = {};
Object.keys(refDims).forEach(r => refDimsOut[r] = [...refDims[r]]);
Object.keys(refVals).forEach(r => refValsOut[r] = [...refVals[r]]);
writeFileSync(join(__dir, 'ref_dims.js'),
  '// AUTO-GENERATED by _gen_obs_meta.mjs — obsId 被哪些維度引用(REF_DIMS) + 哪些 match 值被用到(REF_VALS)\n' +
  'window.REF_DIMS = ' + JSON.stringify(refDimsOut) + ';\n' +
  'window.REF_VALS = ' + JSON.stringify(refValsOut) + ';\n');

console.log('layout parts:', Object.keys(layout).length,
  '| sections:', Object.values(layout).reduce((a, s) => a + s.length, 0),
  '| refd obsIds:', Object.keys(refDimsOut).length);
console.log('wrote questions_layout.js + ref_dims.js');
