// p2/js/_gen_meta.mjs — 產生編輯器要用的靜態資料：
//   p2/js/observations_data.js  (138 筆 observations，離線可用)
//   p2/js/dims_meta.js          (13 維度 + 固定部位骨架)
// 純讀 p2/seed/observations.json + js/core.js(DIMS) + p2_seed live(pos/neg type)。
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DIMS } from '../../js/core.js';

const __dir = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dir, '..', '..');
const obs = JSON.parse(readFileSync(join(REPO, 'p2', 'seed', 'observations.json'), 'utf8'));
const live = JSON.parse(readFileSync(join(REPO, 'p2_seed', 'rbf1_settings_rules.json'), 'utf8'));

writeFileSync(join(__dir, 'observations_data.js'),
  '// AUTO-GENERATED by _gen_meta.mjs — 勿手改\nwindow.OBSERVATIONS = ' + JSON.stringify(obs) + ';\n');

// 固定骨架（v0.6 §3/§4）：13 維、各維同一組部位
const LEAF_PARTS = [
  { name: '頂骨', paired: true }, { name: '枕骨', paired: false }, { name: '華陽骨', paired: true },
  { name: '上停', paired: false }, { name: '耳', paired: true }, { name: '眉', paired: true },
  { name: '眼', paired: true }, { name: '鼻', paired: false }, { name: '口', paired: false },
  { name: '顴', paired: true }, { name: '人中', paired: false }, { name: '地閣', paired: false }, { name: '頤', paired: true }
];
const AGGREGATES = [
  { name: '頭', children: ['頂骨', '枕骨', '華陽骨'] },
  { name: '中停', children: ['眉', '眼', '鼻', '顴'] },
  { name: '下停', children: ['口', '人中', '地閣', '頤'] }
];
const SCORED = ['頭', '上停', '耳', '眉', '眼', '鼻', '口', '中停', '下停'];
// 規則部位名 → observation 的解剖部位名（編輯器預設過濾用）
const PART_TO_OBSPART = {
  頂骨: '頭', 枕骨: '頭', 華陽骨: '頭', 頭: '頭', 上停: '額', 耳: '耳', 眉: '眉', 眼: '眼',
  鼻: '鼻', 口: '口', 顴: '顴', 人中: '人中', 地閣: '地閣', 頤: '頤'
};

const dims = DIMS.map((d, i) => ({
  index: i,
  name: d.dn,
  a: d.a, b: d.b,           // 兩極名（形/勢…）
  aT: d.aT, bT: d.bT,       // 各極的動靜（預設：a=aT、b=bT）
  positiveType: live[i].positiveType,
  negativeType: live[i].negativeType,
  category: d.cat,
  view: d.view
}));

const meta = { dims, leafParts: LEAF_PARTS, aggregates: AGGREGATES, scored: SCORED, partToObsPart: PART_TO_OBSPART };
writeFileSync(join(__dir, 'dims_meta.js'),
  '// AUTO-GENERATED by _gen_meta.mjs — 勿手改\nwindow.DIMS_META = ' + JSON.stringify(meta, null, 1) + ';\n');

console.log('observations:', obs.length, '| dims:', dims.length, '| leafParts:', LEAF_PARTS.length, '| aggregates:', AGGREGATES.length);
console.log('wrote p2/js/observations_data.js + p2/js/dims_meta.js');
