// AUTO-GENERATED by _gen_meta.mjs — 勿手改
window.DIMS_META = {
 "dims": [
  {
   "index": 0,
   "name": "形勢",
   "a": "形",
   "b": "勢",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "先天指數",
   "view": "格局"
  },
  {
   "index": 1,
   "name": "經緯",
   "a": "經",
   "b": "緯",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "先天指數",
   "view": "核心價值"
  },
  {
   "index": 2,
   "name": "方圓",
   "a": "圓",
   "b": "方",
   "aT": "動",
   "bT": "靜",
   "positiveType": "動",
   "negativeType": "靜",
   "category": "先天指數",
   "view": "成就"
  },
  {
   "index": 3,
   "name": "曲直",
   "a": "直",
   "b": "曲",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "先天指數",
   "view": "責任"
  },
  {
   "index": 4,
   "name": "收放",
   "a": "收",
   "b": "放",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "先天指數",
   "view": "能耐"
  },
  {
   "index": 5,
   "name": "緩急",
   "a": "緩",
   "b": "急",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "先天指數",
   "view": "成敗"
  },
  {
   "index": 6,
   "name": "順逆",
   "a": "順",
   "b": "逆",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "運氣指數",
   "view": "天運天機"
  },
  {
   "index": 7,
   "name": "分合",
   "a": "合",
   "b": "分",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "運氣指數",
   "view": "地運資源"
  },
  {
   "index": 8,
   "name": "真假",
   "a": "真",
   "b": "假",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "運氣指數",
   "view": "人運人和"
  },
  {
   "index": 9,
   "name": "攻守",
   "a": "攻",
   "b": "守",
   "aT": "動",
   "bT": "靜",
   "positiveType": "動",
   "negativeType": "靜",
   "category": "後天指數",
   "view": "戰略"
  },
  {
   "index": 10,
   "name": "奇正",
   "a": "奇",
   "b": "正",
   "aT": "動",
   "bT": "靜",
   "positiveType": "動",
   "negativeType": "靜",
   "category": "後天指數",
   "view": "戰術"
  },
  {
   "index": 11,
   "name": "虛實",
   "a": "實",
   "b": "虛",
   "aT": "靜",
   "bT": "動",
   "positiveType": "靜",
   "negativeType": "動",
   "category": "後天指數",
   "view": "算略"
  },
  {
   "index": 12,
   "name": "進退",
   "a": "進",
   "b": "退",
   "aT": "動",
   "bT": "靜",
   "positiveType": "動",
   "negativeType": "靜",
   "category": "後天指數",
   "view": "智略"
  }
 ],
 "leafParts": [
  {
   "name": "頂骨",
   "paired": true
  },
  {
   "name": "枕骨",
   "paired": false
  },
  {
   "name": "華陽骨",
   "paired": true
  },
  {
   "name": "上停",
   "paired": false
  },
  {
   "name": "耳",
   "paired": true
  },
  {
   "name": "眉",
   "paired": true
  },
  {
   "name": "眼",
   "paired": true
  },
  {
   "name": "鼻",
   "paired": false
  },
  {
   "name": "口",
   "paired": false
  },
  {
   "name": "顴",
   "paired": true
  },
  {
   "name": "人中",
   "paired": false
  },
  {
   "name": "地閣",
   "paired": false
  },
  {
   "name": "頤",
   "paired": true
  }
 ],
 "aggregates": [
  {
   "name": "頭",
   "children": [
    "頂骨",
    "枕骨",
    "華陽骨"
   ]
  },
  {
   "name": "中停",
   "children": [
    "眉",
    "眼",
    "鼻",
    "顴"
   ]
  },
  {
   "name": "下停",
   "children": [
    "口",
    "人中",
    "地閣",
    "頤"
   ]
  }
 ],
 "scored": [
  "頭",
  "上停",
  "耳",
  "眉",
  "眼",
  "鼻",
  "口",
  "中停",
  "下停"
 ],
 "partToObsPart": {
  "頂骨": "頭",
  "枕骨": "頭",
  "華陽骨": "頭",
  "頭": "頭",
  "上停": "額",
  "耳": "耳",
  "眉": "眉",
  "眼": "眼",
  "鼻": "鼻",
  "口": "口",
  "顴": "顴",
  "人中": "人中",
  "地閣": "地閣",
  "頤": "頤"
 }
};
